"""empty message

Revision ID: 661556a6f183
Revises: 0fcf62c7234e
Create Date: 2023-04-10 19:08:16.063840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661556a6f183'
down_revision = '0fcf62c7234e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
